language: java
jdk:
- oraclejdk8
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./build/web/WEB-INF/lib"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/install_compose.sh ; fi
before_script:
- echo "Prepare to run the script section"
script:
- echo "Compile Project"
- echo "Execute Various Tests"
- echo "Do More Checks"
after_success:
- openssl aes-256-cbc -K $encrypted_4cc90241bacd_key -iv $encrypted_4cc90241bacd_iv -in deployment_keys.tar.enc -out deployment_keys.tar -d
- echo "Add script or change dockerhub.sh to have the docker build process working for this project"
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- echo "Tidy Up"
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
