analyticsservice:
  image: slidewiki/analyticsservice:latest-dev
  restart: on-failure:5
  expose:
    - "8080"
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=analyticsservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=analyticsservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - SERVICE_URL_ACTIVITIES=https://activitiesservice.experimental.slidewiki.org
